### ISSUE TITLE
from where i can get the access token

### ISSUE THREAD

**Issue by yaseenayahya** [EnderDragonneau/Pi-Network-SDK#1]
Request handler on initialize asking for 
this.accessToken = parsedData.accessToken;
        this.backendURL = parsedData.backendURL;
        this.frontendURL = parsedData.frontendURL;

**Comment by EnderDragonneau** [comment]
This information is brought directly by the Pi Developer Sandbox when it runs your application (it is available in the passed hidden URL). For more information, please refer to the SDK documentation to learn how it works (https://developers.minepi.com/doc/javascript). I also invite you to study how their sandbox works with their test application (https://developers.minepi.com/sandbox/RIenDLItpJuPnG1x6XGmFPqCZAZWm2r54QlDT4Py2eHg).
